/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘UFT-Exercise3.st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir15 = null;
        public BindDirection bind_dir16 = null;
        public HP.ST.Ext.BasicActivities.DataCursorActivity DataCursorActivity16 = null;
        public BindDirection bind_dir17 = null;
        public HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy DataCursorActivity16_Policy = null;
        public BindDirection bind_dir18 = null;
        public BindDirection bind_dir19 = null;
        public BindDirection bind_dir20 = null;
        public BindDirection bind_dir21 = null;
        public BindDirection bind_dir22 = null;
        public BindDirection bind_dir23 = null;
        public BindDirection bind_dir24 = null;
        public BindDirection bind_dir25 = null;
        public BindDirection bind_dir26 = null;
        public BindDirection bind_dir27 = null;
        public BindDirection bind_dir28 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.DataFetchActivity12 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity12");
            _flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.For);
            _flow.DataExporterActivity14 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity14");
            _flow.DataExporterCloseActivity15 = new HP.ST.Ext.BasicActivities.DataExporterCloseActivity(_context,"DataExporterCloseActivity15");
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.DataDisconnectActivity13 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity13");
            this.DataCursorActivity16 = new HP.ST.Ext.BasicActivities.DataCursorActivity(_context,"DataCursorActivity16");
            this.DataCursorActivity16_Policy = new HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy();
            _flow.Sequence11 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence11");
            _flow.StServiceCallActivity4 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity4");
            _flow.StServiceCallActivity9 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity9");
            _flow.StServiceCallActivity10 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity10");
            _flow.DataFetchActivity12.Comment = @"";
            _flow.DataFetchActivity12.IconPath = @"";
            _flow.DataFetchActivity12.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity12.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity12_QueryParameters_Document = new XmlDocument();
            DataFetchActivity12_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity12Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>2811a251-2855-4a71-9600-d98ea6ec2ec6</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>AppData!Sheet1</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>True</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>AppData</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{AppData!Sheet1.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Sheet1$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity12_QueryParameters_Document.LoadXml(xmlDataFetchActivity12Params);
            _flow.DataFetchActivity12.QueryParameters = DataFetchActivity12_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("AppData!Sheet1", _flow.DataFetchActivity12);
            this.Activities.Add (_flow.DataFetchActivity12);
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"Run for 5 iterations";
            _flow.Loop2.NumberOfIterations = (int)5;
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (this.DataCursorActivity16);
            _flow.Loop2.Activities.Add (_flow.Sequence11);
            this.Activities.Add (_flow.Loop2);
            _flow.DataExporterActivity14.Comment = @"";
            _flow.DataExporterActivity14.IconPath = @"";
            VTDPropertyInfoBase pi29 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter15 = new VTDObjectGetter(pi29);
            VTDPropertyInfoBase pi30 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter15 = new VTDObjectSetter(pi30);
            binding_setter15 = new StringFormaterDecorator(binding_setter15,"{Step.DataFetchActivity12.OutTable}");
            bind_dir15 = new BindDirection(_flow.DataFetchActivity12,binding_getter15,binding_setter15,BindTargetType.ToInProperty);
            _flow.DataExporterActivity14.InDirections.Add(bind_dir15);
            this.Activities.Add (_flow.DataExporterActivity14);
            _flow.DataExporterCloseActivity15.Comment = @"";
            _flow.DataExporterCloseActivity15.IconPath = @"";
            this.Activities.Add (_flow.DataExporterCloseActivity15);
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.DataDisconnectActivity13.Comment = @"";
            _flow.DataDisconnectActivity13.IconPath = @"";
            VTDPropertyInfoBase pi31 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter16 = new VTDObjectGetter(pi31);
            VTDPropertyInfoBase pi32 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter16 = new VTDObjectSetter(pi32);
            binding_setter16 = new StringFormaterDecorator(binding_setter16,"{Step.DataFetchActivity12.OutTable}");
            bind_dir16 = new BindDirection(_flow.DataFetchActivity12,binding_getter16,binding_setter16,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity13.InDirections.Add(bind_dir16);
            this.Activities.Add (_flow.DataDisconnectActivity13);
            this.DataCursorActivity16.Comment = @"";
            this.DataCursorActivity16.IconPath = @"";
            VTDPropertyInfoBase pi33 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter17 = new VTDObjectGetter(pi33);
            VTDPropertyInfoBase pi34 = new VTDPropertyInfoBase("InTable");
            VTDBaseSetter binding_setter17 = new VTDObjectSetter(pi34);
            binding_setter17 = new StringFormaterDecorator(binding_setter17,"{Step.DataFetchActivity12.OutTable}");
            bind_dir17 = new BindDirection(_flow.DataFetchActivity12,binding_getter17,binding_setter17,BindTargetType.ToInProperty);
            this.DataCursorActivity16.InDirections.Add(bind_dir17);
            this.DataCursorActivity16_Policy.StartPosition = CursorStartPosition.FirstRecord;
            this.DataCursorActivity16_Policy.StartAtSpecificRow = 1;
            this.DataCursorActivity16_Policy.StartCondition.ColumnName = "";
            this.DataCursorActivity16_Policy.StartCondition.Comparison = ConditionOperator.Equal;
            this.DataCursorActivity16_Policy.StartCondition.Value = "";
            this.DataCursorActivity16_Policy.EndPosition = CursorEndPosition.LastRecord;
            this.DataCursorActivity16_Policy.EndAtSpecificRow = 1;
            this.DataCursorActivity16_Policy.EndCondition.ColumnName = "";
            this.DataCursorActivity16_Policy.EndCondition.Comparison = ConditionOperator.Equal;
            this.DataCursorActivity16_Policy.EndCondition.Value = "";
            this.DataCursorActivity16_Policy.StepType = CursorStepType.Forward;
            this.DataCursorActivity16_Policy.StepSize = 1;
            this.DataCursorActivity16_Policy.ActionAfterLastRecord = CursorActionAfterLastRecord.Wraparound;
            this.DataCursorActivity16.Policy = this.DataCursorActivity16_Policy;
            this.DataCursorActivity16.ReportStepData = true;
            _flow.Loop2.BeforeExecuteStepEvent += this.DataCursorActivity16.ResetCursor;
            _flow.Sequence11.Comment = @"";
            _flow.Sequence11.IconPath = @"";
            _flow.Sequence11.Name = @"Sequence11";
            _flow.Sequence11.Activities.Add (_flow.StServiceCallActivity4);
            _flow.Sequence11.Activities.Add (_flow.StServiceCallActivity9);
            _flow.Sequence11.Activities.Add (_flow.StServiceCallActivity10);
            XmlDocument StServiceCallActivity4_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity4_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity4_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><AccountCreateRequest xmlns=""com.advantage.online.store.accountservice""><lastName>{DataSource.AppData!Sheet1.LastName}</lastName><firstName>{DataSource.AppData!Sheet1.FirstName}</firstName><loginName>{DataSource.AppData!Sheet1.LoginName}</loginName><countryId>40</countryId><stateProvince /><cityName /><address /><zipcode /><phoneNumber /><email>{DataSource.AppData!Sheet1.Email}</email><password>{DataSource.AppData!Sheet1.Password}</password><accountType>20</accountType><allowOffersPromotion>true</allowOffersPromotion></AccountCreateRequest></Body></Envelope>");
            _flow.StServiceCallActivity4.InputEnvelope = StServiceCallActivity4_InputEnvelope_Document;
            _flow.StServiceCallActivity4.Comment = @"";
            _flow.StServiceCallActivity4.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity4.Name = @"AccountCreate";
            _flow.StServiceCallActivity4.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity4.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://nimbusserver:8001/accountservice/" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity4.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity4.TransportProtocol.SOAPProperties.SoapAction = @"";
            _flow.StServiceCallActivity4.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity4.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity4.Service = @"AccountServicePortService";
            _flow.StServiceCallActivity4.Port = @"AccountServicePortSoap11";
            _flow.StServiceCallActivity4.Operation = @"AccountCreate";
            _flow.StServiceCallActivity4.IsOneWay = false;
            _flow.StServiceCallActivity4.SendRequestToService=true;
            _flow.StServiceCallActivity4.FaultExpected=false;
            _flow.StServiceCallActivity4.IsAsync=false;
            _flow.StServiceCallActivity4.TargetNamespace=@"com.advantage.online.store.accountservice";
            _flow.StServiceCallActivity4.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi35 = new VTDPropertyInfoBase("Password");
            VTDBaseGetter binding_getter18 = new VTDObjectGetter(pi35);
            VTDPropertyInfoBase pi36 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateRequest'][1]/*[local-name(.)='password'][1]");
            VTDBaseSetter binding_setter18 = new VTDXPathSetter(pi36,XmlTypeCode.String);
            binding_setter18 = new StringFormaterDecorator(binding_setter18,"{DataSource.AppData!Sheet1.Password}");
            bind_dir18 = new BindDirection(this.DataCursorActivity16,binding_getter18,binding_setter18,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity4.InDirections.Add(bind_dir18);
            VTDPropertyInfoBase pi37 = new VTDPropertyInfoBase("LoginName");
            VTDBaseGetter binding_getter19 = new VTDObjectGetter(pi37);
            VTDPropertyInfoBase pi38 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateRequest'][1]/*[local-name(.)='loginName'][1]");
            VTDBaseSetter binding_setter19 = new VTDXPathSetter(pi38,XmlTypeCode.String);
            binding_setter19 = new StringFormaterDecorator(binding_setter19,"{DataSource.AppData!Sheet1.LoginName}");
            bind_dir19 = new BindDirection(this.DataCursorActivity16,binding_getter19,binding_setter19,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity4.InDirections.Add(bind_dir19);
            VTDPropertyInfoBase pi39 = new VTDPropertyInfoBase("LastName");
            VTDBaseGetter binding_getter20 = new VTDObjectGetter(pi39);
            VTDPropertyInfoBase pi40 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateRequest'][1]/*[local-name(.)='lastName'][1]");
            VTDBaseSetter binding_setter20 = new VTDXPathSetter(pi40,XmlTypeCode.String);
            binding_setter20 = new StringFormaterDecorator(binding_setter20,"{DataSource.AppData!Sheet1.LastName}");
            bind_dir20 = new BindDirection(this.DataCursorActivity16,binding_getter20,binding_setter20,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity4.InDirections.Add(bind_dir20);
            VTDPropertyInfoBase pi41 = new VTDPropertyInfoBase("FirstName");
            VTDBaseGetter binding_getter21 = new VTDObjectGetter(pi41);
            VTDPropertyInfoBase pi42 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateRequest'][1]/*[local-name(.)='firstName'][1]");
            VTDBaseSetter binding_setter21 = new VTDXPathSetter(pi42,XmlTypeCode.String);
            binding_setter21 = new StringFormaterDecorator(binding_setter21,"{DataSource.AppData!Sheet1.FirstName}");
            bind_dir21 = new BindDirection(this.DataCursorActivity16,binding_getter21,binding_setter21,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity4.InDirections.Add(bind_dir21);
            VTDPropertyInfoBase pi43 = new VTDPropertyInfoBase("Email");
            VTDBaseGetter binding_getter22 = new VTDObjectGetter(pi43);
            VTDPropertyInfoBase pi44 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateRequest'][1]/*[local-name(.)='email'][1]");
            VTDBaseSetter binding_setter22 = new VTDXPathSetter(pi44,XmlTypeCode.String);
            binding_setter22 = new StringFormaterDecorator(binding_setter22,"{DataSource.AppData!Sheet1.Email}");
            bind_dir22 = new BindDirection(this.DataCursorActivity16,binding_getter22,binding_setter22,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity4.InDirections.Add(bind_dir22);
            XmlDocument StServiceCallActivity4_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity4_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity4_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity4.ExpectedOutputAttachments = StServiceCallActivity4_ExpectedOutputAttachments_Document;
            XmlDocument StServiceCallActivity4_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity4_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity4_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity4.ExpectedFaultProperties = StServiceCallActivity4_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity4_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity4_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity4_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><AccountCreateResponse xmlns=""com.advantage.online.store.accountservice""><StatusMessage><success>true</success><userId>0</userId><reason /><token /><sessionId /></StatusMessage></AccountCreateResponse></Body></Envelope>");
            _flow.StServiceCallActivity4.ExpectedOutputProperties = StServiceCallActivity4_ExpectedOutputProperties_Document;
            set_StServiceCallActivity4_checkpoints(_flow.StServiceCallActivity4);
            XmlDocument StServiceCallActivity9_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity9_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity9_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><AddSafePayMethodRequest xmlns=""com.advantage.online.store.accountservice""><accountId>{Step.OutputProperties.StServiceCallActivity4.Body.AccountCreateResponse.StatusMessage.userId}</accountId><safePayUsername>{Step.InputProperties.StServiceCallActivity4.Body.AccountCreateRequest.loginName}</safePayUsername><safePayPassword>{Step.InputProperties.StServiceCallActivity4.Body.AccountCreateRequest.password}</safePayPassword><base64Token>{Step.OutputProperties.StServiceCallActivity4.Body.AccountCreateResponse.StatusMessage.userId}</base64Token></AddSafePayMethodRequest></Body></Envelope>");
            _flow.StServiceCallActivity9.InputEnvelope = StServiceCallActivity9_InputEnvelope_Document;
            _flow.StServiceCallActivity9.Comment = @"";
            _flow.StServiceCallActivity9.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity9.Name = @"AddSafePayMethod";
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity9.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://nimbusserver:8001/accountservice/" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity9.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.SoapAction = @"";
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity9.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity9.Service = @"AccountServicePortService";
            _flow.StServiceCallActivity9.Port = @"AccountServicePortSoap11";
            _flow.StServiceCallActivity9.Operation = @"AddSafePayMethod";
            _flow.StServiceCallActivity9.IsOneWay = false;
            _flow.StServiceCallActivity9.SendRequestToService=true;
            _flow.StServiceCallActivity9.FaultExpected=false;
            _flow.StServiceCallActivity9.IsAsync=false;
            _flow.StServiceCallActivity9.TargetNamespace=@"com.advantage.online.store.accountservice";
            _flow.StServiceCallActivity9.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi45 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateRequest'][1]/*[local-name(.)='loginName'][1]");
            VTDBaseGetter binding_getter23 = new VTDXPathGetter(pi45,XmlTypeCode.String);
            VTDPropertyInfoBase pi46 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AddSafePayMethodRequest'][1]/*[local-name(.)='safePayUsername'][1]");
            VTDBaseSetter binding_setter23 = new VTDXPathSetter(pi46,XmlTypeCode.String);
            binding_setter23 = new StringFormaterDecorator(binding_setter23,"{Step.InputProperties.StServiceCallActivity4.Body.AccountCreateRequest.loginName}");
            bind_dir23 = new BindDirection(_flow.StServiceCallActivity4,binding_getter23,binding_setter23,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity9.InDirections.Add(bind_dir23);
            VTDPropertyInfoBase pi47 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateRequest'][1]/*[local-name(.)='password'][1]");
            VTDBaseGetter binding_getter24 = new VTDXPathGetter(pi47,XmlTypeCode.String);
            VTDPropertyInfoBase pi48 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AddSafePayMethodRequest'][1]/*[local-name(.)='safePayPassword'][1]");
            VTDBaseSetter binding_setter24 = new VTDXPathSetter(pi48,XmlTypeCode.String);
            binding_setter24 = new StringFormaterDecorator(binding_setter24,"{Step.InputProperties.StServiceCallActivity4.Body.AccountCreateRequest.password}");
            bind_dir24 = new BindDirection(_flow.StServiceCallActivity4,binding_getter24,binding_setter24,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity9.InDirections.Add(bind_dir24);
            VTDPropertyInfoBase pi49 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateResponse'][1]/*[local-name(.)='StatusMessage'][1]/*[local-name(.)='userId'][1]");
            VTDBaseGetter binding_getter25 = new VTDXPathGetter(pi49,XmlTypeCode.Long);
            VTDPropertyInfoBase pi50 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AddSafePayMethodRequest'][1]/*[local-name(.)='base64Token'][1]");
            VTDBaseSetter binding_setter25 = new VTDXPathSetter(pi50,XmlTypeCode.String);
            binding_setter25 = new StringFormaterDecorator(binding_setter25,"{Step.OutputProperties.StServiceCallActivity4.Body.AccountCreateResponse.StatusMessage.userId}");
            bind_dir25 = new BindDirection(_flow.StServiceCallActivity4,binding_getter25,binding_setter25,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity9.InDirections.Add(bind_dir25);
            VTDPropertyInfoBase pi51 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateResponse'][1]/*[local-name(.)='StatusMessage'][1]/*[local-name(.)='userId'][1]");
            VTDBaseGetter binding_getter26 = new VTDXPathGetter(pi51,XmlTypeCode.Long);
            VTDPropertyInfoBase pi52 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AddSafePayMethodRequest'][1]/*[local-name(.)='accountId'][1]");
            VTDBaseSetter binding_setter26 = new VTDXPathSetter(pi52,XmlTypeCode.Long);
            bind_dir26 = new BindDirection(_flow.StServiceCallActivity4,binding_getter26,binding_setter26,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity9.InDirections.Add(bind_dir26);
            XmlDocument StServiceCallActivity9_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity9_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity9_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity9.ExpectedOutputAttachments = StServiceCallActivity9_ExpectedOutputAttachments_Document;
            XmlDocument StServiceCallActivity9_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity9_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity9_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity9.ExpectedFaultProperties = StServiceCallActivity9_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity9_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity9_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity9_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><AddSafePayMethodResponse xmlns=""com.advantage.online.store.accountservice""><StatusMessage><success>true</success><id /><reason /></StatusMessage></AddSafePayMethodResponse></Body></Envelope>");
            _flow.StServiceCallActivity9.ExpectedOutputProperties = StServiceCallActivity9_ExpectedOutputProperties_Document;
            set_StServiceCallActivity9_checkpoints(_flow.StServiceCallActivity9);
            XmlDocument StServiceCallActivity10_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity10_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity10_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><AccountDeleteRequest xmlns=""com.advantage.online.store.accountservice""><accountId>{Step.OutputProperties.StServiceCallActivity4.Body.AccountCreateResponse.StatusMessage.userId}</accountId><base64Token>{Step.OutputProperties.StServiceCallActivity4.Body.AccountCreateResponse.StatusMessage.userId}</base64Token></AccountDeleteRequest></Body></Envelope>");
            _flow.StServiceCallActivity10.InputEnvelope = StServiceCallActivity10_InputEnvelope_Document;
            _flow.StServiceCallActivity10.Comment = @"";
            _flow.StServiceCallActivity10.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity10.Name = @"AccountDelete";
            _flow.StServiceCallActivity10.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity10.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://nimbusserver:8001/accountservice/" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity10.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity10.TransportProtocol.SOAPProperties.SoapAction = @"";
            _flow.StServiceCallActivity10.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity10.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity10.Service = @"AccountServicePortService";
            _flow.StServiceCallActivity10.Port = @"AccountServicePortSoap11";
            _flow.StServiceCallActivity10.Operation = @"AccountDelete";
            _flow.StServiceCallActivity10.IsOneWay = false;
            _flow.StServiceCallActivity10.IsSkip = true;
            _flow.StServiceCallActivity10.SendRequestToService=true;
            _flow.StServiceCallActivity10.FaultExpected=false;
            _flow.StServiceCallActivity10.IsAsync=false;
            _flow.StServiceCallActivity10.TargetNamespace=@"com.advantage.online.store.accountservice";
            _flow.StServiceCallActivity10.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi53 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateResponse'][1]/*[local-name(.)='StatusMessage'][1]/*[local-name(.)='userId'][1]");
            VTDBaseGetter binding_getter27 = new VTDXPathGetter(pi53,XmlTypeCode.Long);
            VTDPropertyInfoBase pi54 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountDeleteRequest'][1]/*[local-name(.)='base64Token'][1]");
            VTDBaseSetter binding_setter27 = new VTDXPathSetter(pi54,XmlTypeCode.String);
            binding_setter27 = new StringFormaterDecorator(binding_setter27,"{Step.OutputProperties.StServiceCallActivity4.Body.AccountCreateResponse.StatusMessage.userId}");
            bind_dir27 = new BindDirection(_flow.StServiceCallActivity4,binding_getter27,binding_setter27,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity10.InDirections.Add(bind_dir27);
            VTDPropertyInfoBase pi55 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountCreateResponse'][1]/*[local-name(.)='StatusMessage'][1]/*[local-name(.)='userId'][1]");
            VTDBaseGetter binding_getter28 = new VTDXPathGetter(pi55,XmlTypeCode.Long);
            VTDPropertyInfoBase pi56 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='AccountDeleteRequest'][1]/*[local-name(.)='accountId'][1]");
            VTDBaseSetter binding_setter28 = new VTDXPathSetter(pi56,XmlTypeCode.Long);
            bind_dir28 = new BindDirection(_flow.StServiceCallActivity4,binding_getter28,binding_setter28,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity10.InDirections.Add(bind_dir28);
            XmlDocument StServiceCallActivity10_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity10_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity10_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity10.ExpectedOutputAttachments = StServiceCallActivity10_ExpectedOutputAttachments_Document;
            XmlDocument StServiceCallActivity10_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity10_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity10_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity10.ExpectedFaultProperties = StServiceCallActivity10_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity10_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity10_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity10_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><AccountDeleteResponse xmlns=""com.advantage.online.store.accountservice""><StatusMessage><success>true</success><userId /><reason /><token /><sessionId /></StatusMessage></AccountDeleteResponse></Body></Envelope>");
            _flow.StServiceCallActivity10.ExpectedOutputProperties = StServiceCallActivity10_ExpectedOutputProperties_Document;
            set_StServiceCallActivity10_checkpoints(_flow.StServiceCallActivity10);
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(),@"bin\ReportResources");                
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    